title: Programación desde cero - Patricia E. Miguel
description: Recursos educativos sobre programación e informática.
author: Patricia E. Miguel
logo: /static/img/avatar.png
github: https://github.com/programacion-desde-cero
about: Recursos educativos sobre programación e informática.

baseurl: "https://patriciaemiguel.com"
url: "https://patriciaemiguel.com"

allowsearch: true

disqus_shortname: patr1c1a
google_analytics: UA-76752123-1

share:
  twitter_username: Programacion_0
  fb_appid: 000000000000
  
enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme_mode: dark
